#!/usr/bin/env python3

# Print out the provided runtime args, connect to a BenchBot instance, then exit
# cleanly

from benchbot_api import BenchBot
import sys

if __name__ == '__main__':
    print(
        "%s\n%s\n\t%s" %
        ("Welcome to your submission. We received the following arguments via",
         "the --args flag:", sys.argv))

    print("\nStarting and exiting a BenchBot connection:")
    BenchBot()
